
spring:
  jackson:
    time-zone: Asia/Kolkata
  datasource:
    url: jdbc:postgresql://172.17.64.142:5432/signal-db
    username: postgres_ib_uat
    password: 1BzG1U8wXMyNxGsu
#    url: jdbc:postgresql://signal_db:5432/signal_dev
#    username: dev_admin
#    password: bps@1122
    driver-class-name: "org.postgresql.Driver"
    profiles:
      active: uatprod
    hikari:
      connection-timeout: 26000
      idle-timeout: 30000
      leak-detection-threshold: 300
      maximum-pool-size: 50
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: signal
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: signal
  data:
    redis:
      host: 172.17.64.141
      port: 6379
      timeout: 60000ms
      connect-timeout: 10000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 10
          max-wait: 5000ms
        shutdown-timeout: 250ms
      password: "ba5fb0a30e26e83b2ac5b9e29e1b161e5c"

server:
  port: 8082
  servlet:
    context-path: /ql

logging:
  file:
    name: logs/spring-logs.log
  logback:
      rollingpolicy:
        file-name-pattern: logs/signal-quantlogs-%d{yyyy-MM-dd}.log
        max-history: 365
        total-size-cap: 100MB
        max-file-size: 100MB
  level:
    com:
      zaxxer:
        hikari: trace
    root: info
    org:
      hibernate:
        sql: info
        sql2o: info
      springframework: info
    sql: info

grpc:
  client:
    grpc-quantlab-service-xts:
      address: static://172.17.64.141:9000
      negotiation-type: plaintext
    grpc-quantlab-service-tr:
      address: static://172.17.64.141:9040
      negotiation-type: plaintext
    grpc-quantlab-service-tr-stt:
      address: static://172.17.64.141:9050
      negotiation-type: plaintext

xts:
  location: "172.17.64.141"
  port: 9000
tr:
  location: "172.17.64.141"
  port: 9040
tr-stt:
  location: "172.17.64.141"
  port: 9050

email:
  sender: mohammedimran0266@gmail.com

ENDPOINT:
  validate: https://ssologin-uat.ibullssecurities.com/v1/partner/validate-session?clientId=
  profile: https://internal-partner-uat.ibullssecurities.com/client-profile?clientId=
  appID: quantlab
  appKey: mtOwyowygskpv8r6is6kddxhjanvsbsl
  xtsUrl: https://xts-uat.ibullssecurities.com

threads:
  pool:
    Pnl: 1
