version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPOSITORY: signal-app
    EC2_INSTANCE_ID: i-028d6adbca69395e0

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
      - 'echo "ECR URI: $ECR_URI"'
      - 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com'

  build:
    commands:
      - echo "Build started on $(date)"
      - chmod +x gradlew
      - ./gradlew app:bootJar --stacktrace
      - echo "Building Docker image..."
      - 'docker build -t $ECR_URI:$CODEBUILD_BUILD_NUMBER .'
      - 'docker tag $ECR_URI:$CODEBUILD_BUILD_NUMBER $ECR_URI:latest'

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - 'docker push $ECR_URI:$CODEBUILD_BUILD_NUMBER'
      - 'docker push $ECR_URI:latest'

      - echo "Starting deployment on EC2 through SSM..."
      - |
        aws ssm send-command \
          --instance-ids "$EC2_INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "cd /opt/signal",
            "aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 921829859169.dkr.ecr.ap-south-1.amazonaws.com",
            "sudo docker compose pull signal_app",
            "sudo docker compose up -d signal_app",
            "sudo docker compose ps"
          ]' \
          --region "$AWS_REGION"

      - echo "Build and deployment command submitted on $(date)"