version: "3.8"

services:
  signal_app:
    image: 205930636356.dkr.ecr.ap-south-1.amazonaws.com/dev-signal-engine-indiabulls-repo:latest
    ports:
      - "8081:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_network

  signal_db:
    image: postgres:14
    environment:
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: bps@1122
      POSTGRES_DB: signal_dev
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
