services:
  signal_app:
    image: dev-signal-local:latest
    ports:
      - "8081:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=uatprod
    networks:
      - app_network2
  signal_db:
    image: postgres:14
    environment:
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: bps@1122
      POSTGRES_DB: signal_dev
    ports:
      - "5430:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network2

networks:
  app_network2:
    driver: bridge
